// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Palavra Viva - Transforme sua Vida Espiritual",
  description: "Aprenda a ler, interpretar e aplicar a Bíblia em sua vida diária com devocionais personalizados que tocam sua alma e curam suas feridas mais profundas.",
  keywords: "bíblia, devocionais, estudo bíblico, fé, crescimento espiritual, interpretação bíblica, oração, transformação",
  authors: [{ name: "Palavra Viva" }],
  openGraph: {
    title: "Palavra Viva - Descubra o Poder Transformador da Palavra de Deus",
    description: "Devocionais personalizados que tocam sua alma e curam suas feridas mais profundas. Mais de 50k vidas transformadas.",
    type: "website",
    locale: "pt_BR",
  },
  twitter: {
    card: "summary_large_image",
    title: "Palavra Viva - Transforme sua Vida Espiritual",
    description: "Devocionais personalizados que tocam sua alma. Comece grátis por 7 dias.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <link rel="icon" href="/icon.svg" type="image/svg+xml" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}